version: '3.8'

services:
  db:
    image: jmartynova123/dev-lab3-db
    environment:
      POSTGRES_DB: times
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d times"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    image: jmartynova123/dev-lab3-back
    environment:
      DATABASE_URI: postgres://myuser:mypassword@db:5432/times
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/times || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./backend/logs:/var/log/backend  # Монтируем директорию для логов бэкенда

  frontend:
    image: jmartynova123/dev-lab3-front
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
        restart: true
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:3000 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
    # volumes:
    #   - ./frontend/logs:/var/log/frontend  # Монтируем директорию для логов фронтенда

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yml
      - ./backend/logs:/var/log/backend  # Монтируем логи бэкенда
      #- ./frontend/logs:/var/log/frontend  # Монтируем логи фронтенда
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3001"  # Измените порт, чтобы не конфликтовать с фронтендом
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      loki:
        condition: service_healthy