version: '3.8'

services:
  db:
    image: jmartynova123/dev-lab3-db:latest
    environment:
      POSTGRES_DB: times
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d times"]
      interval: 5s             
      timeout: 5s
      retries: 10              
      start_period: 10s 
    networks:
      - my_app_network       

  backend:
    image: jmartynova123/dev-lab3-back:latest
    environment:
      DATABASE_URI: postgresql://myuser:mypassword@db:5432/times
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/times || exit 1"]  
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s        
    volumes:
      - ./visits:/usr/local/app/visits
    networks:
      - my_app_network        

  frontend:
    image: jmartynova123/dev-lab3-front:latest
    ports:
      - "3000:3000"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:3000 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - my_app_network

networks:
  my_app_network:
    driver: bridge
