apiVersion: v1
kind: Secret
metadata:
  name: my-app-secret  
type: Opaque
data:
  POSTGRES_USER: {{ .Values.global.database.user | b64enc }}     
  POSTGRES_PASSWORD: {{ .Values.global.database.password | b64enc }}
  POSTGRES_DB: {{ .Values.global.database.name | b64enc }}      
