apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: jmartynova123/dev-lab3-back:latest
          env:
            - name: DATABASE_URI
              value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@db-service:5432/times"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /times
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /times
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
