apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-svc
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
  selector:
    app: {{ .Release.Name }}-backend
