apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-post-install-hook
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"  # Runs after other resources
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: post-install
        image: alpine:3.18
        command: ["/bin/sh", "-c", "sleep 20"]
      restartPolicy: Never
