apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-pre-install-hook
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"  # Runs before other resources
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: pre-install
        image: alpine:3.18
        command: ["/bin/sh", "-c", "sleep 20"]
      restartPolicy: Never
